# Primer parcial
### Area y perimetros de triángulos
### Lista de elementos a una matriz 4x4
### Calcular la determinante

In [ ]:
# Fórmula de áreas, perimetros de triangulos equilateros
import numpy as Octavius
#Importar los datos con el nombre de Octavius

class Examen():
  def __init__(self):
    print("Examen Parcial")


In [ ]:
examen = Examen()

Examen Parcial


In [ ]:
class Triangulo(Examen):

  def __init__(self):
    Examen.__init__(self)
    print("Clase heredada de triangulo")

  def ap_triangulo(self):
    lado = int(input("Ingrese un valor "))
    h = ((lado*Octavius.sqrt(3))/2)
    area = (lado*2*Octavius.sqrt(3)/4)
    perimetro = 3*lado

    #Regresar los datos con el valor dado por el usuario
    print("Su triangulo de ", lado, "por lado tiene los siguientes valores: ")
    print("El área es:", area)
    print("El perimetro es:", perimetro)


In [ ]:
triangulo = Triangulo()

Examen Parcial
Clase heredada de triangulo


In [ ]:
triangulo.ap_triangulo()

Ingrese un valor 2
Su triangulo de  2 por lado tiene los siguientes valores: 
El área es: 1.7320508075688772
El perimetro es: 6


In [158]:
class Matriz(Examen):

  def __init__(self):
    Examen.__init__(self)
    print("Clase heredada de la Matriz")

    def matriz(self, numeros):
        print(Octavius.array(numeros).reshape(4, 4))

    def determinante(self,Primer):
        print(Octavius.linalg.det(Primer))

class TranformarMatriz(Matriz):
        def __init__(self, numeros):
            self.numeros = numeros

        def tranformar(self):
            return Octavius.array(self.numeros).reshape(4,4)

class CalculadoraDeterminante():
    def __init__(self,matriz):
      Examen.__init__(self)
      self.matriz = matriz

      def determinante(self):
        print(np.linalg.det(matriz))

In [ ]:
matriz = Matriz()

Examen Parcial
Clase heredada de la Matriz


In [163]:
numeros = [i for i in range (1,17)]
transformador = TranformarMatriz(numeros)
matriz = transformador.tranformar()
print("Matriz 4x4: ")
print(matriz)

Matriz 4x4: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
