# Primer parcial
### Area y perimetros de triángulos
### Lista de elementos a una matriz 4x4
### Calcular la determinante

In [196]:
# Fórmula de áreas, perimetros de triangulos equilateros
import numpy as Octavius
#Importar los datos con el nombre de Octavius

class Examen():
  def __init__(self):
    print("Examen Parcial")


In [197]:
examen = Examen()

Examen Parcial


In [198]:
class Triangulo(Examen):

  def __init__(self):
    Examen.__init__(self)
    print("Clase heredada de triangulo")

  def ap_triangulo(self):
    lado = int(input("Ingrese un valor "))
    h = ((lado*Octavius.sqrt(3))/2)
    area = (lado*2*Octavius.sqrt(3)/4)
    perimetro = 3*lado

    #Regresar los datos con el valor dado por el usuario
    print("Su triangulo de ", lado, "por lado tiene los siguientes valores: ")
    print("El área es:", area)
    print("El perimetro es:", perimetro)


In [199]:
triangulo = Triangulo()

Examen Parcial
Clase heredada de triangulo


In [200]:
triangulo.ap_triangulo()

Ingrese un valor 3
Su triangulo de  3 por lado tiene los siguientes valores: 
El área es: 2.598076211353316
El perimetro es: 9


In [213]:
class Matriz(Examen):

  def __init__(self):
    Examen.__init__(self)
    print("Clase heredada de la Matriz")

    def matriz(self, numeros):
        print(Octavius.array(numeros).reshape(4, 4))

    def determinante(self,Primer):
        print(Octavius.linalg.det(Primer))

class TransformarMatriz(Matriz):
        def __init__(self, numeros):
            self.numeros = numeros

        def transformar(self):
            return Octavius.array(self.numeros).reshape(4,4)

class CalcularDeterminante():
    def __init__(self, matriz, determinante):
      Examen.__init__(self)
      self.matriz = matriz

      def determinante():
        print(Octavius.linalg.det(matriz))

In [202]:
matriz = Matriz()

Examen Parcial
Clase heredada de la Matriz


In [203]:
numeros = [i for i in range (1,17)]
transformador = TransformarMatriz(numeros)
matriz = transformador.transformar()
print("Matriz 4x4: ")
print(matriz)

Matriz 4x4: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [214]:
calculador = CalcularDeterminante(matriz)
determinante = calculador.determinante()
print("Determinante:", determinante)

TypeError: CalcularDeterminante.__init__() missing 1 required positional argument: 'determinante'